name: Update NPM Package

on:
  workflow_dispatch:

jobs:
  update-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: oap75/homebrew-tap
          event-type: update-package
